# UNO: known-causal-effect simulation benchmark

This notebook runs the source-preserving scripts in `simulation_benchmark/scripts/`.
It uses fully simulated data and does not require clinical data or the existing
repository demo files. **Restart the kernel, then run the cells in order.**

The source's numerical parameters, random seeds, random-number call order,
optimizer settings, selection rules, and estimators are retained. The original
notebook is archived under `reference/`; it is not used to supply fitted values.

**Default scope:** primary benchmark plus the source's current **100%** development-NCO
replacement setting. A separate, explicitly enabled cell replays all six fractions
shown in the source's accumulated output: 10%, 25%, 50%, 75%, 90%, and 100%.

**Reproducibility:** use `environment.yml` / `requirements.txt` to match the recorded
software versions as closely as possible. Matching seeds alone is not a verified
promise of matching archived outputs in a different software or hardware environment.
The final cells compare fresh results with saved displays and export the actual run.

In [1]:
from pathlib import Path
import sys

# Support launching Jupyter from this folder or from the repository root.
_uno_candidates = (Path.cwd(), Path.cwd() / "simulation_benchmark")
_uno_root = next((p.resolve() for p in _uno_candidates
                  if (p / "workflow.py").is_file()
                  and (p / "reference/source_manifest.json").is_file()), None)
if _uno_root is None:
    raise FileNotFoundError("Open Jupyter in simulation_benchmark or its parent repository folder.")
if str(_uno_root) not in sys.path:
    sys.path.insert(0, str(_uno_root))

from workflow import run_stage, SENSITIVITY_STAGES
from verify_source import verify_source

# Verifies all scientific statements and their original order, before fitting.
_uno_source_check = verify_source()
print("Scientific source preserved:", _uno_source_check["scientific_ast_equivalent"])
print("Nonempty original code cells:", _uno_source_check["nonempty_original_code_cells"])
print("Benchmark directory:", _uno_root)

Scientific source preserved: True
Nonempty original code cells: 31
Benchmark directory: /Users/yuewudb/UNO_revision_ex/benchmark/simulation_benchmark

## 1. Imports and unchanged numerical helpers

Load the network classes, nonlinear score functions, IPW risk-ratio estimator,
Gaussian-null fitting, and EASE. Retain one CPU thread, deterministic Torch
algorithms, the original dtypes, and the post-ReLU activation score.

In [2]:
run_stage("01_setup", globals())

{'python': '3.11.0', 'numpy': '1.26.4', 'pandas': '2.2.3', 'scipy': '1.11.4', 'torch': '2.5.1', 'sklearn': '1.2.2', 'statsmodels': '0.14.0'}

## 2. Original data-generating mechanism

Generate 10,000 individuals, 20 observed covariates, five unmeasured variables,
and 80 NCOs; retain the original 40/40 development/test split.

The executable NCO-parameter seed is **2026**, not the value mentioned in an
outdated source markdown cell. The initial outcome uses `Y_GAMMA_U = 0.2`;
the final target-outcome override is intentionally retained in section 8.
This initial outcome is not used for propensity-score training or NCO selection.

In [3]:
run_stage("02_generate_data", globals())

X64, U shapes: (10000, 20) (10000, 5)

  score  sample_mean  sample_sd
0  C(X)    -0.226824   0.974241
1  S(X)    -0.252741   1.079201
2  V(U)    -0.075072   0.793616

A prevalence: 0.4028 | true gate proportion: 0.3007
e_true_xu quantiles: [0.05011401 0.05475955 0.354548   0.93793454 0.94990217]
W shape: (10000, 80) | prevalence range: 0.065 0.1999
True marginal RR: 0.75
Mean risks under A=0 / A=1: 0.0807447583833364 0.06055856878750231
Observed Y events: 716
Xt, At: torch.Size([10000, 20]) torch.Size([10000, 1])
Eligible / development / held-out NCOs: 80 40 40

## 3. Logistic-regression propensity scores

Fit the original observed-covariate logistic comparator. Do not supply U.

In [4]:
run_stage("03_logistic_ps", globals())

Logistic treatment accuracy: 0.6414
Logistic PS range: 0.07180967155903815 0.8294408205808129

## 4. Base neural network

Initialize and fit the original 100-by-100-by-100 ReLU network for up to 50 epochs.
Retain the original initialization, batch order, dropout, Adam settings, learning-rate
schedule, accuracy-based stopping rule, fitted weights, and post-training RNG state.
The training loop remains explicit in the script.

In [5]:
run_stage("04_base_model", globals())

PS(
  (stack): ModuleList(
    (0): Linear(in_features=20, out_features=100, bias=True)
    (1-2): 2 x Linear(in_features=100, out_features=100, bias=True)
    (3): Linear(in_features=100, out_features=1, bias=True)
  )
  (act): ReLU()
  (dropout): Dropout(p=0.1, inplace=False)
  (sigmoid): Sigmoid()
)
Base 01/50  loss=0.64818  accuracy=0.6592  lr=0.001
Base 02/50  loss=0.62475  accuracy=0.6746  lr=0.001
Base 03/50  loss=0.61690  accuracy=0.6836  lr=0.001
Base 04/50  loss=0.60758  accuracy=0.6877  lr=0.001
Base 05/50  loss=0.60298  accuracy=0.6998  lr=0.001
Base 06/50  loss=0.59445  accuracy=0.7068  lr=0.001
Base 07/50  loss=0.59106  accuracy=0.7135  lr=0.001
Base 08/50  loss=0.58453  accuracy=0.7143  lr=0.001
Base 09/50  loss=0.57788  accuracy=0.7211  lr=0.001
Base 10/50  loss=0.57214  accuracy=0.7338  lr=0.0005
Base 11/50  loss=0.55793  accuracy=0.7442  lr=0.0005
Base 12/50  loss=0.55009  accuracy=0.7493  lr=0.0005
Base 13/50  loss=0.54775  accuracy=0.7538  lr=0.0005
Base 14/50  loss=0.54064  accuracy=0.7592  lr=0.0005
Base 15/50  loss=0.53815  accuracy=0.7647  lr=0.0005
Base 16/50  loss=0.53616  accuracy=0.7743  lr=0.0005
Base 17/50  loss=0.52142  accuracy=0.7641  lr=0.0005
Base 18/50  loss=0.52351  accuracy=0.7811  lr=0.0005
Base 19/50  loss=0.52300  accuracy=0.7829  lr=0.0005
Base 20/50  loss=0.51402  accuracy=0.7851  lr=0.00025
Base 21/50  loss=0.50531  accuracy=0.7940  lr=0.00025
Base 22/50  loss=0.50490  accuracy=0.7994  lr=0.00025
Base 23/50  loss=0.49969  accuracy=0.8018  lr=0.00025
Base 24/50  loss=0.49780  accuracy=0.8007  lr=0.00025
Base 25/50  loss=0.49535  accuracy=0.8045  lr=0.00025
Base 26/50  loss=0.49031  accuracy=0.8055  lr=0.00025
Base 27/50  loss=0.49011  accuracy=0.8099  lr=0.00025
Base 28/50  loss=0.48864  accuracy=0.8128  lr=0.00025
Base 29/50  loss=0.49063  accuracy=0.8123  lr=0.00025
Base 30/50  loss=0.48276  accuracy=0.8167  lr=0.00013
Base 31/50  loss=0.48221  accuracy=0.8186  lr=0.00013
Base 32/50  loss=0.47833  accuracy=0.8231  lr=0.00013
Base 33/50  loss=0.47548  accuracy=0.8205  lr=0.00013
Base 34/50  loss=0.47658  accuracy=0.8218  lr=0.00013
Base 35/50  loss=0.46979  accuracy=0.8237  lr=0.00013
Base 36/50  loss=0.47557  accuracy=0.8248  lr=0.00013
Base 37/50  loss=0.47282  accuracy=0.8241  lr=0.00013
Base 38/50  loss=0.47416  accuracy=0.8279  lr=0.00013
Base 39/50  loss=0.47137  accuracy=0.8290  lr=0.00013
Base 40/50  loss=0.46970  accuracy=0.8318  lr=6.3e-05
Base 41/50  loss=0.46970  accuracy=0.8338  lr=6.3e-05
Base 42/50  loss=0.46004  accuracy=0.8332  lr=6.3e-05
Base 43/50  loss=0.46898  accuracy=0.8358  lr=6.3e-05
Base 44/50  loss=0.46222  accuracy=0.8347  lr=6.3e-05
Base 45/50  loss=0.46106  accuracy=0.8328  lr=6.3e-05
Base 46/50  loss=0.46589  accuracy=0.8369  lr=6.3e-05
Base 47/50  loss=0.46372  accuracy=0.8368  lr=6.3e-05
Base 48/50  loss=0.46632  accuracy=0.8371  lr=6.3e-05
Base 49/50  loss=0.46085  accuracy=0.8372  lr=6.3e-05
Base 50/50  loss=0.46392  accuracy=0.8382  lr=3.1e-05
Base training seconds: 6.71

## 5. Development-NCO signals and groups

Fit the original treated/control logistic models. Preserve both the threshold
scan and the subsequent explicit **`threshold_used = 0.08`** override.
Group membership follows the original count cutoff; it is not forced to equal 15%.

In [6]:
run_stage("05_nco_signals", globals())

Development NCO models: 10/40
Development NCO models: 20/40
Development NCO models: 30/40
Development NCO models: 40/40
Automatic signal-threshold calibration (development signals only):

   signal_threshold  count_cutoff  high_fraction  distance_to_target
0          0.079516            16         0.1505              0.0005
1          0.079881            16         0.1492              0.0008
2          0.079152            16         0.1522              0.0022
3          0.080246            16         0.1470              0.0030
4          0.078787            16         0.1540              0.0040

NCO signal threshold used: 0.08 | count cutoff: 16.0
High / low counts: 1484 8516
Actual high proportion: 14.84%
Shapes: torch.Size([1484, 20]) torch.Size([8516, 20]) torch.Size([1484, 1]) torch.Size([8516, 1])

## 6. Original UNO pruning and fine-tuning

Retain candidate fractions **[0.35, 0.40, 0.45, 0.50]** and 15 fine-tuning epochs.
Every candidate starts from the fitted Base weights. Preserve global top-k scoring,
incoming/bias/outgoing masks, gradient masking, the low-signal training subset,
and selection using development NCOs only. The original Base is unchanged.

In [7]:
run_stage("06_uno", globals())

UNO starts from fitted Base: {'in_N': 20, 'm': 100, 'depth': 3, 'dropout': 0.1, 'ps_floor': 0.01}
ratio=0.35: removed=[33, 31, 41], total=105
  UNO 01/15  loss_low=0.59539  accuracy_all=0.7228
  UNO 02/15  loss_low=0.57159  accuracy_all=0.7315
  UNO 03/15  loss_low=0.56768  accuracy_all=0.7269
  UNO 04/15  loss_low=0.56299  accuracy_all=0.7395
  UNO 05/15  loss_low=0.55362  accuracy_all=0.7466
  UNO 06/15  loss_low=0.55083  accuracy_all=0.7479
  UNO 07/15  loss_low=0.55256  accuracy_all=0.7484
  UNO 08/15  loss_low=0.54474  accuracy_all=0.7568
  UNO 09/15  loss_low=0.54352  accuracy_all=0.7603
  UNO 10/15  loss_low=0.53817  accuracy_all=0.7606
  UNO 11/15  loss_low=0.52302  accuracy_all=0.7734
  UNO 12/15  loss_low=0.51748  accuracy_all=0.7737
  UNO 13/15  loss_low=0.51833  accuracy_all=0.7769
  UNO 14/15  loss_low=0.50720  accuracy_all=0.7754
  UNO 15/15  loss_low=0.50659  accuracy_all=0.7801
  development EASE: 0.21502161100133618
ratio=0.40: removed=[37, 36, 47], total=120
  UNO 01/15  loss_low=0.61099  accuracy_all=0.7118
  UNO 02/15  loss_low=0.58225  accuracy_all=0.7201
  UNO 03/15  loss_low=0.57507  accuracy_all=0.7296
  UNO 04/15  loss_low=0.56986  accuracy_all=0.7312
  UNO 05/15  loss_low=0.56309  accuracy_all=0.7337
  UNO 06/15  loss_low=0.55728  accuracy_all=0.7379
  UNO 07/15  loss_low=0.55297  accuracy_all=0.7457
  UNO 08/15  loss_low=0.54749  accuracy_all=0.7490
  UNO 09/15  loss_low=0.54175  accuracy_all=0.7549
  UNO 10/15  loss_low=0.54351  accuracy_all=0.7558
  UNO 11/15  loss_low=0.52945  accuracy_all=0.7658
  UNO 12/15  loss_low=0.52840  accuracy_all=0.7685
  UNO 13/15  loss_low=0.52008  accuracy_all=0.7714
  UNO 14/15  loss_low=0.52075  accuracy_all=0.7699
  UNO 15/15  loss_low=0.51831  accuracy_all=0.7732
  development EASE: 0.19219106112781062
ratio=0.45: removed=[42, 40, 53], total=135
  UNO 01/15  loss_low=0.62204  accuracy_all=0.6844
  UNO 02/15  loss_low=0.59472  accuracy_all=0.7081
  UNO 03/15  loss_low=0.58241  accuracy_all=0.7185
  UNO 04/15  loss_low=0.57523  accuracy_all=0.7191
  UNO 05/15  loss_low=0.57552  accuracy_all=0.7296
  UNO 06/15  loss_low=0.56681  accuracy_all=0.7346
  UNO 07/15  loss_low=0.56428  accuracy_all=0.7371
  UNO 08/15  loss_low=0.56056  accuracy_all=0.7373
  UNO 09/15  loss_low=0.55369  accuracy_all=0.7459
  UNO 10/15  loss_low=0.55340  accuracy_all=0.7529
  UNO 11/15  loss_low=0.54142  accuracy_all=0.7548
  UNO 12/15  loss_low=0.54246  accuracy_all=0.7515
  UNO 13/15  loss_low=0.53333  accuracy_all=0.7557
  UNO 14/15  loss_low=0.52949  accuracy_all=0.7616
  UNO 15/15  loss_low=0.52772  accuracy_all=0.7647
  development EASE: 0.17960191823189114
ratio=0.50: removed=[48, 44, 58], total=150
  UNO 01/15  loss_low=0.63303  accuracy_all=0.6756
  UNO 02/15  loss_low=0.60262  accuracy_all=0.6882
  UNO 03/15  loss_low=0.58988  accuracy_all=0.7065
  UNO 04/15  loss_low=0.58539  accuracy_all=0.7108
  UNO 05/15  loss_low=0.58170  accuracy_all=0.7170
  UNO 06/15  loss_low=0.57360  accuracy_all=0.7202
  UNO 07/15  loss_low=0.57215  accuracy_all=0.7088
  UNO 08/15  loss_low=0.57136  accuracy_all=0.7209
  UNO 09/15  loss_low=0.56694  accuracy_all=0.7311
  UNO 10/15  loss_low=0.56559  accuracy_all=0.7315
  UNO 11/15  loss_low=0.55766  accuracy_all=0.7374
  UNO 12/15  loss_low=0.55592  accuracy_all=0.7394
  UNO 13/15  loss_low=0.54857  accuracy_all=0.7398
  UNO 14/15  loss_low=0.55055  accuracy_all=0.7458
  UNO 15/15  loss_low=0.54695  accuracy_all=0.7454
  development EASE: 0.23321435131177995
Selected pruning ratio (development EASE only): 0.45

   ratio  pruning_only_dev_EASE  UNO_dev_EASE
0   0.35               0.440166      0.215022
1   0.40               0.495105      0.192191
2   0.45               0.502365      0.179602
3   0.50               0.471195      0.233214

   ratio     start_widths        pruned      retained
0   0.35  [100, 100, 100]  [33, 31, 41]  [67, 69, 59]
1   0.40  [100, 100, 100]  [37, 36, 47]  [63, 64, 53]
2   0.45  [100, 100, 100]  [42, 40, 53]  [58, 60, 47]
3   0.50  [100, 100, 100]  [48, 44, 58]  [52, 56, 42]

## 7. Held-out NCO evaluation

Evaluate the same 40 held-out NCOs for all original comparators, including the true-PS oracle.

In [8]:
run_stage("07_heldout_evaluation", globals())

                 method  n_heldout_ncos  heldout_EASE  null_mean   null_sd
0            Unadjusted              40      0.535613   0.535613  0.037922
1           Logistic PS              40      0.348938   0.348938  0.051016
2               Base NN              40      0.250688   0.250688  0.044391
3          Pruning only              40      0.495193   0.495193  0.065958
4                   UNO              40      0.190230   0.190213  0.058329
5  Oracle true PS (X,U)              40      0.071144  -0.063987  0.056233

## 8. Final target outcome and single-realization RR

Preserve the original later override: **`Y_GAMMA_U = 2`**, **`Y_USE_V1 = True`**.
The quadratic score uses all five unmeasured variables and cohort-fixed normalization.
The true conditional and marginal causal RR is **0.75**.

The source retains the initial outcome in `df["Y"]`; downstream target-effect
calculations explicitly use the later `Y` variable. This distinction is preserved,
not silently repaired or reordered. There is no trimming or extra post-fit clipping.

In [9]:
run_stage("08_target_outcome", globals())

True marginal RR: 0.75
Mean risks under A=0 / A=1: 0.12130943934383093 0.0909820795078732
Observed Y events: 1053

,method,n_used,RR_hat,true_RR,RR_error,abs_RR_error,log_rr_se_model
0,Unadjusted,10000,1.106434,0.75,0.356434,0.356434,0.062294
1,Logistic PS,10000,0.944480,0.75,0.194480,0.194480,0.043579
2,Base NN,10000,0.854634,0.75,0.104634,0.104634,0.048270
3,Pruning only,10000,1.030579,0.75,0.280579,0.280579,0.040251
4,UNO,10000,0.709005,0.75,-0.040995,0.040995,0.045365
5,"Oracle true PS (X,U)",10000,0.683581,0.75,-0.066419,0.066419,0.044005

## 9. NCO-only empirical calibration

Fit the Gaussian systematic-error model using development NCOs for Base NN and
Logistic PS. The point-estimate adjustment subtracts the fitted null mean on the
log-RR scale. It does not modify propensity scores or weights. EC rows retain the
parent model's pre-calibration held-out EASE.

In [10]:
run_stage("09_empirical_calibration", globals())

Same current Y: single-run RR and estimation errors (not repeated-Y averages):

,method,heldout_EASE_before_EC,n_used,true_RR,RR_hat,RR_error,abs_RR_error
0,Unadjusted,0.535613,10000,0.75,1.106434,0.356434,0.356434
1,Logistic PS,0.348938,10000,0.75,0.944480,0.194480,0.194480
2,Base NN,0.250688,10000,0.75,0.854634,0.104634,0.104634
3,Pruning only,0.495193,10000,0.75,1.030579,0.280579,0.280579
4,UNO,0.190230,10000,0.75,0.709005,-0.040995,0.040995
5,"Oracle true PS (X,U)",0.071144,10000,0.75,0.683581,-0.066419,0.066419
6,Base NN + EC (NCO-only),0.250688,10000,0.75,0.668413,-0.081587,0.081587
7,Logistic PS + EC (NCO-only),0.348938,10000,0.75,0.671795,-0.078205,0.078205

Same current Y: calibrated intervals (95%):

,method,RR_before_EC,RR_EC,CI_lower_EC,CI_upper_EC,p_EC
0,Base NN + EC (NCO-only),0.854634,0.668413,0.587412,0.760585,9.831646e-10
1,Logistic PS + EC (NCO-only),0.944480,0.671795,0.593868,0.759948,2.555095e-10

Development-NCO calibration parameters (log-RR scale):

,method,n_development_NCOs,mu_full,tau_full,mu_RR,tau_RR,n_RR_patients
0,Base NN + EC (NCO-only),40,0.245766,0.044879,0.245766,0.044879,10000
1,Logistic PS + EC (NCO-only),40,0.340681,0.045368,0.340681,0.045368,10000

Single-run errors are not Bias/MAE/RMSE across repeated datasets.
CIs retain the original model-based SE and treat calibration parameters as fixed.

## 10. Paired target-outcome realizations

Generate the original **1,000 outcome-only realizations**, holding the cohort and
fitted models fixed. Use the same realization for every method. Retain all original
RR, MAE, RMSE, conditional-bias, calibration, and paired-comparison calculations.
These are not 1,000 independently generated cohorts or model refits.

In [11]:
run_stage("10_repeated_outcomes", globals())

                 method  heldout_EASE   mean_rr   bias_rr    mae_rr   rmse_rr
0            Unadjusted      0.535613  1.100114  0.350114  0.350114  0.353798
1           Logistic PS      0.348938  0.949849  0.199849  0.199849  0.205205
2               Base NN      0.250688  0.875081  0.125081  0.125311  0.135511
3          Pruning only      0.495193  1.093173  0.343173  0.343173  0.348571
4                   UNO      0.190230  0.803900  0.053900  0.059480  0.071769
5  Oracle true PS (X,U)      0.071144  0.726909 -0.023091  0.039588  0.048693

Maximum weighted-Poisson check error: 7.771561172376096e-15
Outcome-only repeats; independent full datasets = 1.
Same Y replicates for all methods; EC uses fixed development-NCO parameters:

,method,n_y_replicates,heldout_EASE_before_EC,mean_rr,bias_rr,mae_rr,rmse_rr
0,Unadjusted,1000,0.535613,1.100114,0.350114,0.350114,0.353798
1,Logistic PS,1000,0.348938,0.949849,0.199849,0.199849,0.205205
2,Base NN,1000,0.250688,0.875081,0.125081,0.125311,0.135511
3,Pruning only,1000,0.495193,1.093173,0.343173,0.343173,0.348571
4,UNO,1000,0.190230,0.803900,0.053900,0.059480,0.071769
5,"Oracle true PS (X,U)",1000,0.071144,0.726909,-0.023091,0.039588,0.048693
6,Base NN + EC (NCO-only),1000,0.250688,0.684405,-0.065595,0.067403,0.077235
7,Logistic PS + EC (NCO-only),1000,0.348938,0.675614,-0.074386,0.074778,0.081430

The first EC replicate matches the single-Y EC result.
EC rows inherit the original held-out EASE of their parent methods.
Outcome-only repeats; independent full datasets = 1.

,comparison,fraction_UNO_lower_abs_error,MAE_difference_UNO_minus_baseline,MSE_difference_UNO_minus_baseline,relative_RMSE_reduction
0,UNO vs Logistic PS,0.998,-0.140369,-0.036958,0.650254
1,UNO vs Base NN,0.965,-0.065831,-0.013212,0.470378

## 11. Original sensitivity parameters

The uploaded source currently sets **`NCO25_REPLACEMENT_FRACTION = 1`** (100%).
The inherited `NCO25_` names are retained for source compatibility; they do not
force the replacement fraction to be 25%. Both perturbation seeds remain 2026.

In [13]:
run_stage("11_sensitivity_parameters", globals())

## 12. Development-NCO perturbation

Regenerate only the selected development NCOs with their direct U coefficients
set to zero. Retain all other coefficients without prevalence matching. The
remaining development NCOs and all held-out NCOs remain unchanged. No new
cohort, Base model, or target-outcome realizations are created.

For a deliberate alternative setting, change `NCO25_REPLACEMENT_FRACTION`
**after section 11**, then run sections 12–14. To preserve the source default,
leave it at 1. All replacement subsets are drawn using the original code.

In [14]:
run_stage("12_sensitivity_data", globals())

Fixed cohort: n=10000; existing Y realizations=1000
Replace 40/40 development NCOs; retain all 40 held-out NCOs.
Original Base parameters, predictions, data and Y realizations will not be overwritten.

,nco,df_column_index,replaced,original_U_loading,scenario_U_loading,prevalence_original,prevalence_scenario,prevalence_treated,prevalence_control,estimable
0,W38,58,True,0.988957,0.0,0.1122,0.0967,0.128352,0.075352,True
1,W65,85,True,1.110496,0.0,0.1815,0.1702,0.217478,0.138312,True
2,W37,57,True,1.352575,0.0,0.1297,0.1047,0.130338,0.087408,True
3,W04,24,True,1.290683,0.0,0.1074,0.0868,0.106504,0.073510,True
4,W54,74,True,1.108142,0.0,0.1191,0.1007,0.131082,0.080208,True
5,W01,21,True,1.177141,0.0,0.0802,0.0639,0.073982,0.057100,True
6,W41,61,True,1.287191,0.0,0.1512,0.1290,0.167080,0.103315,True
7,W79,99,True,1.082868,0.0,0.0650,0.0547,0.075472,0.040690,True
8,W56,76,True,1.040880,0.0,0.1366,0.1199,0.154419,0.096618,True
9,W32,52,True,1.174736,0.0,0.1801,0.1568,0.201092,0.126926,True
10,W42,62,True,1.226049,0.0,0.1024,0.0839,0.112463,0.064635,True
11,W66,86,True,1.055397,0.0,0.1999,0.1807,0.224926,0.150871,True
12,W76,96,True,1.084402,0.0,0.1301,0.1190,0.158391,0.092431,True
13,W16,36,True,0.936948,0.0,0.1598,0.1513,0.193644,0.122739,True
14,W48,68,True,1.006070,0.0,0.0818,0.0742,0.103277,0.054588,True
15,W53,73,True,1.031342,0.0,0.1167,0.1007,0.143496,0.071835,True
16,W10,30,True,1.132906,0.0,0.1032,0.0861,0.122393,0.061621,True
17,W18,38,True,0.983912,0.0,0.1070,0.0919,0.128848,0.066979,True
18,W64,84,True,1.166224,0.0,0.0749,0.0546,0.069513,0.044541,True
19,W74,94,True,1.184736,0.0,0.1932,0.1709,0.210278,0.144340,True
20,W05,25,True,1.082643,0.0,0.0936,0.0784,0.094340,0.067649,True
21,W26,46,True,1.214154,0.0,0.1041,0.0811,0.101539,0.067314,True
22,W39,59,True,1.044396,0.0,0.1651,0.1616,0.199851,0.135800,True
23,W49,69,True,1.347693,0.0,0.1525,0.1323,0.174777,0.103650,True
24,W34,54,True,1.188540,0.0,0.1302,0.1081,0.134310,0.090422,True
25,W21,41,True,1.258917,0.0,0.1284,0.1050,0.140516,0.081045,True
26,W68,88,True,1.387916,0.0,0.1114,0.0839,0.114697,0.063128,True
27,W08,28,True,0.915232,0.0,0.0743,0.0645,0.080685,0.053583,True
28,W28,48,True,0.939815,0.0,0.1327,0.1174,0.156405,0.091092,True
29,W55,75,True,0.910472,0.0,0.1039,0.1000,0.132820,0.077863,True
30,W03,23,True,1.020313,0.0,0.1140,0.0978,0.130834,0.075519,True
31,W75,95,True,1.143779,0.0,0.1825,0.1695,0.222443,0.133791,True
32,W70,90,True,1.343506,0.0,0.1041,0.0789,0.106008,0.060616,True
33,W52,72,True,1.175688,0.0,0.1054,0.0880,0.117676,0.067984,True
34,W29,49,True,1.231481,0.0,0.1135,0.0985,0.135055,0.073845,True
35,W30,50,True,1.060758,0.0,0.0817,0.0677,0.079692,0.059612,True
36,W57,77,True,1.035340,0.0,0.1282,0.1162,0.154667,0.090255,True
37,W27,47,True,1.269630,0.0,0.0897,0.0732,0.094836,0.058607,True
38,W07,27,True,1.382685,0.0,0.1806,0.1600,0.197865,0.134461,True
39,W02,22,True,1.119073,0.0,0.1404,0.1188,0.146723,0.099967,True

Unchanged: all non-replaced development NCOs and all held-out NCO observations.

## 13. Refit the NCO-guided modification

Repeat NCO prediction, grouping, scoring, pruning, and fine-tuning using the
original rules and candidate fractions. The actual 0.08 signal threshold is
inherited; the count cutoff is recomputed. A degenerate split is reported as an
error rather than silently changing the rule. Development EASE selects the model.

In [15]:
run_stage("13_sensitivity_development", globals())

NCO25: fitted 10/40 development NCO model pairs
NCO25: fitted 20/40 development NCO model pairs
NCO25: fitted 30/40 development NCO model pairs
NCO25: fitted 40/40 development NCO model pairs
Estimated signals may be nonzero even for NCOs with no direct U dependence.

   replaced  n_ncos  mean_absolute_estimated_signal
0      True      40                        0.034198

   signal_threshold  count_offset  count_cutoff  n_high  n_low  high_fraction
0              0.08             3            13     566   9434         0.0566

NOTE: high fraction is outside the original reference range; rule remains unchanged.
Inherited Base architecture: {'in_N': 20, 'm': 100, 'depth': 3, 'dropout': 0.1, 'ps_floor': 0.01}
Candidate ratios: (0.35, 0.4, 0.45, 0.5) | fine-tuning epochs: 15
NCO25 ratio=0.35; removed per layer=[36, 30, 39]
  01/15 loss_low=0.61144 accuracy_all=0.7016
  02/15 loss_low=0.58701 accuracy_all=0.7278
  03/15 loss_low=0.57562 accuracy_all=0.7345
  04/15 loss_low=0.57461 accuracy_all=0.7367
  05/15 loss_low=0.56364 accuracy_all=0.7494
  06/15 loss_low=0.55713 accuracy_all=0.7409
  07/15 loss_low=0.55560 accuracy_all=0.7580
  08/15 loss_low=0.55155 accuracy_all=0.7598
  09/15 loss_low=0.54775 accuracy_all=0.7643
  10/15 loss_low=0.54611 accuracy_all=0.7655
  11/15 loss_low=0.53372 accuracy_all=0.7727
  12/15 loss_low=0.52720 accuracy_all=0.7810
  13/15 loss_low=0.52570 accuracy_all=0.7755
  14/15 loss_low=0.52304 accuracy_all=0.7850
  15/15 loss_low=0.52085 accuracy_all=0.7873
  development EASE: 0.1694747741950022
NCO25 ratio=0.40; removed per layer=[45, 34, 41]
  01/15 loss_low=0.62705 accuracy_all=0.6800
  02/15 loss_low=0.60063 accuracy_all=0.7045
  03/15 loss_low=0.59022 accuracy_all=0.7199
  04/15 loss_low=0.58373 accuracy_all=0.7235
  05/15 loss_low=0.57450 accuracy_all=0.7340
  06/15 loss_low=0.57538 accuracy_all=0.7344
  07/15 loss_low=0.56978 accuracy_all=0.7439
  08/15 loss_low=0.56630 accuracy_all=0.7423
  09/15 loss_low=0.55923 accuracy_all=0.7519
  10/15 loss_low=0.55818 accuracy_all=0.7472
  11/15 loss_low=0.55080 accuracy_all=0.7567
  12/15 loss_low=0.54381 accuracy_all=0.7613
  13/15 loss_low=0.53758 accuracy_all=0.7648
  14/15 loss_low=0.54336 accuracy_all=0.7715
  15/15 loss_low=0.54008 accuracy_all=0.7685
  development EASE: 0.13611482537549538
NCO25 ratio=0.45; removed per layer=[49, 42, 44]
  01/15 loss_low=0.63584 accuracy_all=0.6760
  02/15 loss_low=0.60579 accuracy_all=0.7032
  03/15 loss_low=0.59592 accuracy_all=0.7075
  04/15 loss_low=0.58732 accuracy_all=0.7215
  05/15 loss_low=0.58556 accuracy_all=0.7253
  06/15 loss_low=0.57900 accuracy_all=0.7247
  07/15 loss_low=0.57809 accuracy_all=0.7323
  08/15 loss_low=0.57068 accuracy_all=0.7358
  09/15 loss_low=0.57025 accuracy_all=0.7405
  10/15 loss_low=0.56431 accuracy_all=0.7428
  11/15 loss_low=0.55531 accuracy_all=0.7500
  12/15 loss_low=0.54970 accuracy_all=0.7545
  13/15 loss_low=0.55183 accuracy_all=0.7522
  14/15 loss_low=0.55010 accuracy_all=0.7522
  15/15 loss_low=0.55188 accuracy_all=0.7540
  development EASE: 0.13126089347877554
NCO25 ratio=0.50; removed per layer=[55, 46, 49]
  01/15 loss_low=0.64484 accuracy_all=0.6582
  02/15 loss_low=0.61853 accuracy_all=0.6964
  03/15 loss_low=0.60381 accuracy_all=0.7072
  04/15 loss_low=0.59811 accuracy_all=0.7085
  05/15 loss_low=0.58945 accuracy_all=0.7153
  06/15 loss_low=0.58630 accuracy_all=0.7182
  07/15 loss_low=0.58021 accuracy_all=0.7216
  08/15 loss_low=0.58018 accuracy_all=0.7286
  09/15 loss_low=0.57643 accuracy_all=0.7325
  10/15 loss_low=0.57662 accuracy_all=0.7319
  11/15 loss_low=0.56688 accuracy_all=0.7389
  12/15 loss_low=0.56036 accuracy_all=0.7427
  13/15 loss_low=0.55976 accuracy_all=0.7418
  14/15 loss_low=0.55495 accuracy_all=0.7463
  15/15 loss_low=0.55601 accuracy_all=0.7457
  development EASE: 0.18766912284030193
Selected ratio (development EASE only): 0.45
NCO25 pruning/fine-tuning seconds: 8.8

   ratio  development_EASE removed_per_layer retained_per_layer
0   0.35          0.169475      [36, 30, 39]       [64, 70, 61]
1   0.40          0.136115      [45, 34, 41]       [55, 66, 59]
2   0.45          0.131261      [49, 42, 44]       [51, 58, 56]
3   0.50          0.187669      [55, 46, 49]       [45, 54, 51]

## 14. Evaluate and collect the current sensitivity setting

Compare only the fixed Base Model and this setting's UNO using the original
held-out NCOs and paired outcomes. Integrity checks confirm that the original
arrays, data frame, Base weights, and original UNO predictions are unchanged.

In [16]:
run_stage("14_sensitivity_evaluation", globals())

True RR=0.75; same 1000 paired outcome realizations

,method,heldout_EASE,mean_rr,mae_rr,rmse_rr
0,Base Model,0.250688,0.875081,0.125311,0.135511
1,UNO (100% development NCOs without U),0.236322,0.870925,0.120996,0.129597

,comparison,MAE_difference,MSE_difference,relative_RMSE_reduction,fraction_UNO_lower_absolute_error
0,NCO25 UNO minus Base Model,-0.004315,-0.001568,0.043636,0.56

Original data, fitted Base, original UNO predictions (if present), and Y realizations: unchanged.
One fixed cohort and one specified NCO perturbation; only the original Y realizations are repeated.

,no_U_percent,method,heldout_EASE,mean_rr,mae_rr,rmse_rr
0,100,Base Model,0.250688,0.875081,0.125311,0.135511
1,100,UNO (100% development NCOs without U),0.236322,0.870925,0.120996,0.129597

## 15. Optional: replay all six recorded replacement fractions

The original notebook accumulated these rows by manually rerunning its sensitivity
cells. A fresh run of its saved code only evaluates 100%. Enable the cell below to
replay **10%, 25%, 50%, 75%, 90%, and 100%** using the same Base and the original
sensitivity scripts. No other scientific parameters are changed. Replacement sets
are selected separately, not forced to be nested.

Each completed scenario can be saved with its actual weights and predictions.
This output option changes file saving only, not the analysis. The default is
**False** for the replay itself, preserving the saved source's single-setting run.

In [18]:
RUN_FULL_NCO_SENSITIVITY = True #False
SAVE_EACH_SENSITIVITY_RUN = True

if RUN_FULL_NCO_SENSITIVITY:
    from benchmark_io import save_run
    for _uno_fraction in (0.10, 0.25, 0.50, 0.75, 0.90, 1.0):
        NCO25_REPLACEMENT_FRACTION = _uno_fraction
        print(f"\n--- Replacement fraction: {100 * _uno_fraction:g}% ---")
        # Do not rerun stage 11, which deliberately preserves the source default.
        for _uno_stage in SENSITIVITY_STAGES:
            run_stage(_uno_stage, globals())
        if SAVE_EACH_SENSITIVITY_RUN:
            _uno_saved_fraction = save_run(globals())
            print("Saved this completed setting:", _uno_saved_fraction)
else:
    print("Full fraction replay disabled; the source-default 100% result is retained.")

--- Replacement fraction: 10% ---
Fixed cohort: n=10000; existing Y realizations=1000
Replace 4/40 development NCOs; retain all 40 held-out NCOs.
Original Base parameters, predictions, data and Y realizations will not be overwritten.

,nco,df_column_index,replaced,original_U_loading,scenario_U_loading,prevalence_original,prevalence_scenario,prevalence_treated,prevalence_control,estimable
0,W79,99,True,1.082868,0.0,0.0650,0.0560,0.072244,0.045044,True
1,W56,76,True,1.040880,0.0,0.1366,0.1247,0.163853,0.098292,True
2,W39,59,True,1.044396,0.0,0.1651,0.1728,0.208044,0.149029,True
3,W57,77,True,1.035340,0.0,0.1282,0.1136,0.151440,0.088078,True

Unchanged: all non-replaced development NCOs and all held-out NCO observations.
NCO25: fitted 10/40 development NCO model pairs
NCO25: fitted 20/40 development NCO model pairs
NCO25: fitted 30/40 development NCO model pairs
NCO25: fitted 40/40 development NCO model pairs
Estimated signals may be nonzero even for NCOs with no direct U dependence.

   replaced  n_ncos  mean_absolute_estimated_signal
0     False      36                        0.045463
1      True       4                        0.037264

   signal_threshold  count_offset  count_cutoff  n_high  n_low  high_fraction
0              0.08             3            16    1326   8674         0.1326

Inherited Base architecture: {'in_N': 20, 'm': 100, 'depth': 3, 'dropout': 0.1, 'ps_floor': 0.01}
Candidate ratios: (0.35, 0.4, 0.45, 0.5) | fine-tuning epochs: 15
NCO25 ratio=0.35; removed per layer=[32, 32, 41]
  01/15 loss_low=0.59773 accuracy_all=0.7180
  02/15 loss_low=0.57227 accuracy_all=0.7351
  03/15 loss_low=0.56498 accuracy_all=0.7327
  04/15 loss_low=0.56241 accuracy_all=0.7427
  05/15 loss_low=0.55245 accuracy_all=0.7525
  06/15 loss_low=0.54685 accuracy_all=0.7586
  07/15 loss_low=0.54401 accuracy_all=0.7622
  08/15 loss_low=0.54120 accuracy_all=0.7549
  09/15 loss_low=0.53714 accuracy_all=0.7621
  10/15 loss_low=0.53681 accuracy_all=0.7663
  11/15 loss_low=0.51916 accuracy_all=0.7671
  12/15 loss_low=0.51761 accuracy_all=0.7801
  13/15 loss_low=0.51220 accuracy_all=0.7780
  14/15 loss_low=0.51106 accuracy_all=0.7836
  15/15 loss_low=0.51098 accuracy_all=0.7885
  development EASE: 0.19921417103717146
NCO25 ratio=0.40; removed per layer=[37, 36, 47]
  01/15 loss_low=0.61253 accuracy_all=0.7007
  02/15 loss_low=0.58515 accuracy_all=0.7241
  03/15 loss_low=0.57739 accuracy_all=0.7304
  04/15 loss_low=0.56328 accuracy_all=0.7263
  05/15 loss_low=0.56194 accuracy_all=0.7374
  06/15 loss_low=0.55935 accuracy_all=0.7415
  07/15 loss_low=0.55519 accuracy_all=0.7449
  08/15 loss_low=0.55225 accuracy_all=0.7542
  09/15 loss_low=0.54568 accuracy_all=0.7616
  10/15 loss_low=0.54143 accuracy_all=0.7627
  11/15 loss_low=0.53648 accuracy_all=0.7674
  12/15 loss_low=0.52299 accuracy_all=0.7626
  13/15 loss_low=0.52336 accuracy_all=0.7740
  14/15 loss_low=0.52112 accuracy_all=0.7773
  15/15 loss_low=0.52435 accuracy_all=0.7739
  development EASE: 0.2028931421511553
NCO25 ratio=0.45; removed per layer=[41, 41, 53]
  01/15 loss_low=0.61803 accuracy_all=0.6920
  02/15 loss_low=0.58988 accuracy_all=0.7085
  03/15 loss_low=0.58548 accuracy_all=0.7157
  04/15 loss_low=0.57897 accuracy_all=0.7277
  05/15 loss_low=0.57120 accuracy_all=0.7351
  06/15 loss_low=0.57077 accuracy_all=0.7367
  07/15 loss_low=0.56518 accuracy_all=0.7373
  08/15 loss_low=0.55707 accuracy_all=0.7374
  09/15 loss_low=0.55902 accuracy_all=0.7487
  10/15 loss_low=0.55563 accuracy_all=0.7539
  11/15 loss_low=0.54419 accuracy_all=0.7541
  12/15 loss_low=0.54102 accuracy_all=0.7596
  13/15 loss_low=0.53925 accuracy_all=0.7569
  14/15 loss_low=0.53243 accuracy_all=0.7608
  15/15 loss_low=0.53345 accuracy_all=0.7651
  development EASE: 0.19674469365152278
NCO25 ratio=0.50; removed per layer=[50, 44, 56]
  01/15 loss_low=0.63825 accuracy_all=0.6796
  02/15 loss_low=0.60514 accuracy_all=0.6901
  03/15 loss_low=0.59491 accuracy_all=0.7031
  04/15 loss_low=0.59012 accuracy_all=0.6962
  05/15 loss_low=0.58647 accuracy_all=0.7070
  06/15 loss_low=0.58425 accuracy_all=0.7151
  07/15 loss_low=0.57537 accuracy_all=0.7251
  08/15 loss_low=0.57140 accuracy_all=0.7191
  09/15 loss_low=0.56856 accuracy_all=0.7246
  10/15 loss_low=0.56881 accuracy_all=0.7321
  11/15 loss_low=0.55961 accuracy_all=0.7374
  12/15 loss_low=0.55877 accuracy_all=0.7393
  13/15 loss_low=0.55463 accuracy_all=0.7462
  14/15 loss_low=0.55351 accuracy_all=0.7458
  15/15 loss_low=0.54943 accuracy_all=0.7453
  development EASE: 0.2385764967442726
Selected ratio (development EASE only): 0.45
NCO25 pruning/fine-tuning seconds: 8.37

   ratio  development_EASE removed_per_layer retained_per_layer
0   0.35          0.199214      [32, 32, 41]       [68, 68, 59]
1   0.40          0.202893      [37, 36, 47]       [63, 64, 53]
2   0.45          0.196745      [41, 41, 53]       [59, 59, 47]
3   0.50          0.238576      [50, 44, 56]       [50, 56, 44]

True RR=0.75; same 1000 paired outcome realizations

,method,heldout_EASE,mean_rr,mae_rr,rmse_rr
0,Base Model,0.250688,0.875081,0.125311,0.135511
1,UNO (10% development NCOs without U),0.221743,0.830804,0.082201,0.093935

,comparison,MAE_difference,MSE_difference,relative_RMSE_reduction,fraction_UNO_lower_absolute_error
0,NCO25 UNO minus Base Model,-0.043109,-0.009539,0.30681,0.895

Original data, fitted Base, original UNO predictions (if present), and Y realizations: unchanged.
One fixed cohort and one specified NCO perturbation; only the original Y realizations are repeated.

,no_U_percent,method,heldout_EASE,mean_rr,mae_rr,rmse_rr
0,10,Base Model,0.250688,0.875081,0.125311,0.135511
1,10,UNO (10% development NCOs without U),0.221743,0.830804,0.082201,0.093935
2,100,Base Model,0.250688,0.875081,0.125311,0.135511
3,100,UNO (100% development NCOs without U),0.236322,0.870925,0.120996,0.129597

Saved this completed setting: /Users/yuewudb/UNO_revision_ex/benchmark/simulation_benchmark/results/run_20260926T180445912601Z_23447

--- Replacement fraction: 25% ---
Fixed cohort: n=10000; existing Y realizations=1000
Replace 10/40 development NCOs; retain all 40 held-out NCOs.
Original Base parameters, predictions, data and Y realizations will not be overwritten.

,nco,df_column_index,replaced,original_U_loading,scenario_U_loading,prevalence_original,prevalence_scenario,prevalence_treated,prevalence_control,estimable
0,W37,57,True,1.352575,0.0,0.1297,0.1031,0.129096,0.085566,True
1,W41,61,True,1.287191,0.0,0.1512,0.1283,0.164350,0.103985,True
2,W79,99,True,1.082868,0.0,0.0650,0.0522,0.067776,0.041695,True
3,W32,52,True,1.174736,0.0,0.1801,0.1603,0.197865,0.134963,True
4,W16,36,True,0.936948,0.0,0.1598,0.1493,0.194389,0.118888,True
5,W64,84,True,1.166224,0.0,0.0749,0.0596,0.081182,0.045044,True
6,W21,41,True,1.258917,0.0,0.1284,0.1103,0.140020,0.090255,True
7,W03,23,True,1.020313,0.0,0.1140,0.1002,0.138530,0.074347,True
8,W75,95,True,1.143779,0.0,0.1825,0.1665,0.213257,0.134963,True
9,W27,47,True,1.269630,0.0,0.0897,0.0739,0.108242,0.050737,True

Unchanged: all non-replaced development NCOs and all held-out NCO observations.
NCO25: fitted 10/40 development NCO model pairs
NCO25: fitted 20/40 development NCO model pairs
NCO25: fitted 30/40 development NCO model pairs
NCO25: fitted 40/40 development NCO model pairs
Estimated signals may be nonzero even for NCOs with no direct U dependence.

   replaced  n_ncos  mean_absolute_estimated_signal
0     False      30                        0.045376
1      True      10                        0.036633

   signal_threshold  count_offset  count_cutoff  n_high  n_low  high_fraction
0              0.08             3            14    1394   8606         0.1394

Inherited Base architecture: {'in_N': 20, 'm': 100, 'depth': 3, 'dropout': 0.1, 'ps_floor': 0.01}
Candidate ratios: (0.35, 0.4, 0.45, 0.5) | fine-tuning epochs: 15
NCO25 ratio=0.35; removed per layer=[34, 31, 40]
  01/15 loss_low=0.60337 accuracy_all=0.7123
  02/15 loss_low=0.57578 accuracy_all=0.7192
  03/15 loss_low=0.56871 accuracy_all=0.7318
  04/15 loss_low=0.55906 accuracy_all=0.7307
  05/15 loss_low=0.55575 accuracy_all=0.7461
  06/15 loss_low=0.55559 accuracy_all=0.7487
  07/15 loss_low=0.54723 accuracy_all=0.7469
  08/15 loss_low=0.53990 accuracy_all=0.7590
  09/15 loss_low=0.54077 accuracy_all=0.7557
  10/15 loss_low=0.52961 accuracy_all=0.7667
  11/15 loss_low=0.52323 accuracy_all=0.7764
  12/15 loss_low=0.51519 accuracy_all=0.7781
  13/15 loss_low=0.50958 accuracy_all=0.7728
  14/15 loss_low=0.51117 accuracy_all=0.7817
  15/15 loss_low=0.50780 accuracy_all=0.7837
  development EASE: 0.19862322753558587
NCO25 ratio=0.40; removed per layer=[36, 38, 46]
  01/15 loss_low=0.61311 accuracy_all=0.7098
  02/15 loss_low=0.58527 accuracy_all=0.7165
  03/15 loss_low=0.58145 accuracy_all=0.7229
  04/15 loss_low=0.57042 accuracy_all=0.7280
  05/15 loss_low=0.56168 accuracy_all=0.7377
  06/15 loss_low=0.55628 accuracy_all=0.7373
  07/15 loss_low=0.55604 accuracy_all=0.7454
  08/15 loss_low=0.55310 accuracy_all=0.7521
  09/15 loss_low=0.54512 accuracy_all=0.7555
  10/15 loss_low=0.54339 accuracy_all=0.7571
  11/15 loss_low=0.52796 accuracy_all=0.7594
  12/15 loss_low=0.52838 accuracy_all=0.7604
  13/15 loss_low=0.52346 accuracy_all=0.7673
  14/15 loss_low=0.51984 accuracy_all=0.7706
  15/15 loss_low=0.51694 accuracy_all=0.7702
  development EASE: 0.18281612201631225
NCO25 ratio=0.45; removed per layer=[43, 40, 52]
  01/15 loss_low=0.62734 accuracy_all=0.6887
  02/15 loss_low=0.59461 accuracy_all=0.7035
  03/15 loss_low=0.58574 accuracy_all=0.7110
  04/15 loss_low=0.57692 accuracy_all=0.7158
  05/15 loss_low=0.57327 accuracy_all=0.7209
  06/15 loss_low=0.57011 accuracy_all=0.7270
  07/15 loss_low=0.56421 accuracy_all=0.7296
  08/15 loss_low=0.55984 accuracy_all=0.7401
  09/15 loss_low=0.55475 accuracy_all=0.7406
  10/15 loss_low=0.55296 accuracy_all=0.7470
  11/15 loss_low=0.54382 accuracy_all=0.7513
  12/15 loss_low=0.53965 accuracy_all=0.7539
  13/15 loss_low=0.53626 accuracy_all=0.7543
  14/15 loss_low=0.53755 accuracy_all=0.7600
  15/15 loss_low=0.53292 accuracy_all=0.7629
  development EASE: 0.19166936586540786
NCO25 ratio=0.50; removed per layer=[52, 43, 55]
  01/15 loss_low=0.63467 accuracy_all=0.6679
  02/15 loss_low=0.60851 accuracy_all=0.6879
  03/15 loss_low=0.59845 accuracy_all=0.6979
  04/15 loss_low=0.58898 accuracy_all=0.7007
  05/15 loss_low=0.58971 accuracy_all=0.7086
  06/15 loss_low=0.58158 accuracy_all=0.7143
  07/15 loss_low=0.57913 accuracy_all=0.7099
  08/15 loss_low=0.57524 accuracy_all=0.7115
  09/15 loss_low=0.57378 accuracy_all=0.7207
  10/15 loss_low=0.56866 accuracy_all=0.7232
  11/15 loss_low=0.56243 accuracy_all=0.7306
  12/15 loss_low=0.55754 accuracy_all=0.7337
  13/15 loss_low=0.55786 accuracy_all=0.7360
  14/15 loss_low=0.55258 accuracy_all=0.7377
  15/15 loss_low=0.54850 accuracy_all=0.7415
  development EASE: 0.22109407814427484
Selected ratio (development EASE only): 0.4
NCO25 pruning/fine-tuning seconds: 7.9

   ratio  development_EASE removed_per_layer retained_per_layer
0   0.35          0.198623      [34, 31, 40]       [66, 69, 60]
1   0.40          0.182816      [36, 38, 46]       [64, 62, 54]
2   0.45          0.191669      [43, 40, 52]       [57, 60, 48]
3   0.50          0.221094      [52, 43, 55]       [48, 57, 45]

True RR=0.75; same 1000 paired outcome realizations

,method,heldout_EASE,mean_rr,mae_rr,rmse_rr
0,Base Model,0.250688,0.875081,0.125311,0.135511
1,UNO (25% development NCOs without U),0.219138,0.841341,0.092558,0.105061

,comparison,MAE_difference,MSE_difference,relative_RMSE_reduction,fraction_UNO_lower_absolute_error
0,NCO25 UNO minus Base Model,-0.032753,-0.007325,0.224703,0.854

Original data, fitted Base, original UNO predictions (if present), and Y realizations: unchanged.
One fixed cohort and one specified NCO perturbation; only the original Y realizations are repeated.

,no_U_percent,method,heldout_EASE,mean_rr,mae_rr,rmse_rr
0,10,Base Model,0.250688,0.875081,0.125311,0.135511
1,10,UNO (10% development NCOs without U),0.221743,0.830804,0.082201,0.093935
2,25,Base Model,0.250688,0.875081,0.125311,0.135511
3,25,UNO (25% development NCOs without U),0.219138,0.841341,0.092558,0.105061
4,100,Base Model,0.250688,0.875081,0.125311,0.135511
5,100,UNO (100% development NCOs without U),0.236322,0.870925,0.120996,0.129597

Saved this completed setting: /Users/yuewudb/UNO_revision_ex/benchmark/simulation_benchmark/results/run_20260926T180455593482Z_23447

--- Replacement fraction: 50% ---
Fixed cohort: n=10000; existing Y realizations=1000
Replace 20/40 development NCOs; retain all 40 held-out NCOs.
Original Base parameters, predictions, data and Y realizations will not be overwritten.

,nco,df_column_index,replaced,original_U_loading,scenario_U_loading,prevalence_original,prevalence_scenario,prevalence_treated,prevalence_control,estimable
0,W65,85,True,1.110496,0.0,0.1815,0.1600,0.210526,0.125921,True
1,W54,74,True,1.108142,0.0,0.1191,0.1041,0.142006,0.078533,True
2,W01,21,True,1.177141,0.0,0.0802,0.0635,0.077458,0.054086,True
3,W79,99,True,1.082868,0.0,0.0650,0.0563,0.080189,0.040188,True
4,W32,52,True,1.174736,0.0,0.1801,0.1589,0.200596,0.130777,True
5,W42,62,True,1.226049,0.0,0.1024,0.0794,0.109980,0.058774,True
6,W66,86,True,1.055397,0.0,0.1999,0.1819,0.226415,0.151875,True
7,W76,96,True,1.084402,0.0,0.1301,0.1163,0.154171,0.090757,True
8,W48,68,True,1.006070,0.0,0.0818,0.0733,0.096077,0.057937,True
9,W18,38,True,0.983912,0.0,0.1070,0.0948,0.135303,0.067482,True
10,W64,84,True,1.166224,0.0,0.0749,0.0612,0.079692,0.048727,True
11,W05,25,True,1.082643,0.0,0.0936,0.0796,0.095581,0.068821,True
12,W26,46,True,1.214154,0.0,0.1041,0.0803,0.095829,0.069826,True
13,W39,59,True,1.044396,0.0,0.1651,0.1592,0.193148,0.136303,True
14,W68,88,True,1.387916,0.0,0.1114,0.0842,0.105760,0.069658,True
15,W28,48,True,0.939815,0.0,0.1327,0.1136,0.150447,0.088747,True
16,W52,72,True,1.175688,0.0,0.1054,0.0901,0.122890,0.067984,True
17,W27,47,True,1.269630,0.0,0.0897,0.0724,0.094588,0.057435,True
18,W07,27,True,1.382685,0.0,0.1806,0.1632,0.196624,0.140656,True
19,W02,22,True,1.119073,0.0,0.1404,0.1193,0.152929,0.096618,True

Unchanged: all non-replaced development NCOs and all held-out NCO observations.
NCO25: fitted 10/40 development NCO model pairs
NCO25: fitted 20/40 development NCO model pairs
NCO25: fitted 30/40 development NCO model pairs
NCO25: fitted 40/40 development NCO model pairs
Estimated signals may be nonzero even for NCOs with no direct U dependence.

   replaced  n_ncos  mean_absolute_estimated_signal
0     False      20                        0.046541
1      True      20                        0.033422

   signal_threshold  count_offset  count_cutoff  n_high  n_low  high_fraction
0              0.08             3            13    1164   8836         0.1164

Inherited Base architecture: {'in_N': 20, 'm': 100, 'depth': 3, 'dropout': 0.1, 'ps_floor': 0.01}
Candidate ratios: (0.35, 0.4, 0.45, 0.5) | fine-tuning epochs: 15
NCO25 ratio=0.35; removed per layer=[33, 32, 40]
  01/15 loss_low=0.60597 accuracy_all=0.7152
  02/15 loss_low=0.57332 accuracy_all=0.7304
  03/15 loss_low=0.56893 accuracy_all=0.7262
  04/15 loss_low=0.56428 accuracy_all=0.7381
  05/15 loss_low=0.55215 accuracy_all=0.7414
  06/15 loss_low=0.55071 accuracy_all=0.7551
  07/15 loss_low=0.54203 accuracy_all=0.7574
  08/15 loss_low=0.53667 accuracy_all=0.7643
  09/15 loss_low=0.53117 accuracy_all=0.7591
  10/15 loss_low=0.53522 accuracy_all=0.7712
  11/15 loss_low=0.52173 accuracy_all=0.7726
  12/15 loss_low=0.51236 accuracy_all=0.7805
  13/15 loss_low=0.51473 accuracy_all=0.7816
  14/15 loss_low=0.51090 accuracy_all=0.7814
  15/15 loss_low=0.50652 accuracy_all=0.7826
  development EASE: 0.15086613653432845
NCO25 ratio=0.40; removed per layer=[39, 36, 45]
  01/15 loss_low=0.62483 accuracy_all=0.6807
  02/15 loss_low=0.58742 accuracy_all=0.7125
  03/15 loss_low=0.57748 accuracy_all=0.7209
  04/15 loss_low=0.57365 accuracy_all=0.7213
  05/15 loss_low=0.56917 accuracy_all=0.7411
  06/15 loss_low=0.56249 accuracy_all=0.7380
  07/15 loss_low=0.55501 accuracy_all=0.7431
  08/15 loss_low=0.55390 accuracy_all=0.7496
  09/15 loss_low=0.55342 accuracy_all=0.7523
  10/15 loss_low=0.54768 accuracy_all=0.7572
  11/15 loss_low=0.53741 accuracy_all=0.7670
  12/15 loss_low=0.52955 accuracy_all=0.7710
  13/15 loss_low=0.52460 accuracy_all=0.7697
  14/15 loss_low=0.52273 accuracy_all=0.7748
  15/15 loss_low=0.52370 accuracy_all=0.7757
  development EASE: 0.1664289038496142
NCO25 ratio=0.45; removed per layer=[45, 41, 49]
  01/15 loss_low=0.62994 accuracy_all=0.6851
  02/15 loss_low=0.60241 accuracy_all=0.7065
  03/15 loss_low=0.59293 accuracy_all=0.7082
  04/15 loss_low=0.58431 accuracy_all=0.7142
  05/15 loss_low=0.57568 accuracy_all=0.7212
  06/15 loss_low=0.57252 accuracy_all=0.7264
  07/15 loss_low=0.56688 accuracy_all=0.7315
  08/15 loss_low=0.56357 accuracy_all=0.7317
  09/15 loss_low=0.55777 accuracy_all=0.7408
  10/15 loss_low=0.55684 accuracy_all=0.7364
  11/15 loss_low=0.54437 accuracy_all=0.7428
  12/15 loss_low=0.54477 accuracy_all=0.7516
  13/15 loss_low=0.54261 accuracy_all=0.7532
  14/15 loss_low=0.53664 accuracy_all=0.7557
  15/15 loss_low=0.53758 accuracy_all=0.7584
  development EASE: 0.11598550526396172
NCO25 ratio=0.50; removed per layer=[50, 42, 58]
  01/15 loss_low=0.63822 accuracy_all=0.6765
  02/15 loss_low=0.60832 accuracy_all=0.6918
  03/15 loss_low=0.59569 accuracy_all=0.7011
  04/15 loss_low=0.59027 accuracy_all=0.7062
  05/15 loss_low=0.58435 accuracy_all=0.7120
  06/15 loss_low=0.58198 accuracy_all=0.7192
  07/15 loss_low=0.57897 accuracy_all=0.7197
  08/15 loss_low=0.56842 accuracy_all=0.7278
  09/15 loss_low=0.57076 accuracy_all=0.7286
  10/15 loss_low=0.56260 accuracy_all=0.7267
  11/15 loss_low=0.55867 accuracy_all=0.7373
  12/15 loss_low=0.55370 accuracy_all=0.7421
  13/15 loss_low=0.55365 accuracy_all=0.7453
  14/15 loss_low=0.55017 accuracy_all=0.7472
  15/15 loss_low=0.54826 accuracy_all=0.7483
  development EASE: 0.17808469757442252
Selected ratio (development EASE only): 0.45
NCO25 pruning/fine-tuning seconds: 7.96

   ratio  development_EASE removed_per_layer retained_per_layer
0   0.35          0.150866      [33, 32, 40]       [67, 68, 60]
1   0.40          0.166429      [39, 36, 45]       [61, 64, 55]
2   0.45          0.115986      [45, 41, 49]       [55, 59, 51]
3   0.50          0.178085      [50, 42, 58]       [50, 58, 42]

True RR=0.75; same 1000 paired outcome realizations

,method,heldout_EASE,mean_rr,mae_rr,rmse_rr
0,Base Model,0.250688,0.875081,0.125311,0.135511
1,UNO (50% development NCOs without U),0.170971,0.805899,0.060585,0.072816

,comparison,MAE_difference,MSE_difference,relative_RMSE_reduction,fraction_UNO_lower_absolute_error
0,NCO25 UNO minus Base Model,-0.064726,-0.013061,0.462656,0.954

Original data, fitted Base, original UNO predictions (if present), and Y realizations: unchanged.
One fixed cohort and one specified NCO perturbation; only the original Y realizations are repeated.

,no_U_percent,method,heldout_EASE,mean_rr,mae_rr,rmse_rr
0,10,Base Model,0.250688,0.875081,0.125311,0.135511
1,10,UNO (10% development NCOs without U),0.221743,0.830804,0.082201,0.093935
2,25,Base Model,0.250688,0.875081,0.125311,0.135511
3,25,UNO (25% development NCOs without U),0.219138,0.841341,0.092558,0.105061
4,50,Base Model,0.250688,0.875081,0.125311,0.135511
5,50,UNO (50% development NCOs without U),0.170971,0.805899,0.060585,0.072816
6,100,Base Model,0.250688,0.875081,0.125311,0.135511
7,100,UNO (100% development NCOs without U),0.236322,0.870925,0.120996,0.129597

Saved this completed setting: /Users/yuewudb/UNO_revision_ex/benchmark/simulation_benchmark/results/run_20260926T180505244153Z_23447

--- Replacement fraction: 75% ---
Fixed cohort: n=10000; existing Y realizations=1000
Replace 30/40 development NCOs; retain all 40 held-out NCOs.
Original Base parameters, predictions, data and Y realizations will not be overwritten.

,nco,df_column_index,replaced,original_U_loading,scenario_U_loading,prevalence_original,prevalence_scenario,prevalence_treated,prevalence_control,estimable
0,W38,58,True,0.988957,0.0,0.1122,0.0953,0.124876,0.075352,True
1,W65,85,True,1.110496,0.0,0.1815,0.1713,0.228153,0.132954,True
2,W37,57,True,1.352575,0.0,0.1297,0.1095,0.141509,0.087910,True
3,W04,24,True,1.290683,0.0,0.1074,0.0828,0.103525,0.068821,True
4,W54,74,True,1.108142,0.0,0.1191,0.1010,0.140020,0.074682,True
5,W41,61,True,1.287191,0.0,0.1512,0.1289,0.159633,0.108171,True
6,W56,76,True,1.040880,0.0,0.1366,0.1281,0.161619,0.105492,True
7,W32,52,True,1.174736,0.0,0.1801,0.1591,0.199851,0.131614,True
8,W42,62,True,1.226049,0.0,0.1024,0.0824,0.107746,0.065305,True
9,W66,86,True,1.055397,0.0,0.1999,0.1858,0.225670,0.158908,True
10,W76,96,True,1.084402,0.0,0.1301,0.1203,0.152433,0.098627,True
11,W16,36,True,0.936948,0.0,0.1598,0.1528,0.198361,0.122070,True
12,W48,68,True,1.006070,0.0,0.0818,0.0720,0.099553,0.053416,True
13,W53,73,True,1.031342,0.0,0.1167,0.1017,0.152433,0.067482,True
14,W74,94,True,1.184736,0.0,0.1932,0.1758,0.218719,0.146852,True
15,W05,25,True,1.082643,0.0,0.0936,0.0750,0.083664,0.069156,True
16,W26,46,True,1.214154,0.0,0.1041,0.0770,0.093843,0.065640,True
17,W39,59,True,1.044396,0.0,0.1651,0.1580,0.191907,0.135131,True
18,W49,69,True,1.347693,0.0,0.1525,0.1254,0.159881,0.102143,True
19,W34,54,True,1.188540,0.0,0.1302,0.1097,0.139275,0.089752,True
20,W68,88,True,1.387916,0.0,0.1114,0.0834,0.107746,0.066979,True
21,W08,28,True,0.915232,0.0,0.0743,0.0663,0.092105,0.048895,True
22,W28,48,True,0.939815,0.0,0.1327,0.1193,0.159136,0.092431,True
23,W55,75,True,0.910472,0.0,0.1039,0.1007,0.135799,0.077026,True
24,W75,95,True,1.143779,0.0,0.1825,0.1702,0.223684,0.134126,True
25,W70,90,True,1.343506,0.0,0.1041,0.0829,0.104518,0.068319,True
26,W52,72,True,1.175688,0.0,0.1054,0.0873,0.116931,0.067314,True
27,W29,49,True,1.231481,0.0,0.1135,0.1013,0.140268,0.075017,True
28,W27,47,True,1.269630,0.0,0.0897,0.0696,0.094340,0.052914,True
29,W07,27,True,1.382685,0.0,0.1806,0.1544,0.183714,0.134628,True

Unchanged: all non-replaced development NCOs and all held-out NCO observations.
NCO25: fitted 10/40 development NCO model pairs
NCO25: fitted 20/40 development NCO model pairs
NCO25: fitted 30/40 development NCO model pairs
NCO25: fitted 40/40 development NCO model pairs
Estimated signals may be nonzero even for NCOs with no direct U dependence.

   replaced  n_ncos  mean_absolute_estimated_signal
0     False      10                        0.043803
1      True      30                        0.034908

   signal_threshold  count_offset  count_cutoff  n_high  n_low  high_fraction
0              0.08             3            11    1063   8937         0.1063

Inherited Base architecture: {'in_N': 20, 'm': 100, 'depth': 3, 'dropout': 0.1, 'ps_floor': 0.01}
Candidate ratios: (0.35, 0.4, 0.45, 0.5) | fine-tuning epochs: 15
NCO25 ratio=0.35; removed per layer=[35, 31, 39]
  01/15 loss_low=0.61618 accuracy_all=0.7009
  02/15 loss_low=0.58171 accuracy_all=0.7214
  03/15 loss_low=0.57384 accuracy_all=0.7275
  04/15 loss_low=0.56620 accuracy_all=0.7348
  05/15 loss_low=0.56118 accuracy_all=0.7392
  06/15 loss_low=0.55815 accuracy_all=0.7441
  07/15 loss_low=0.55341 accuracy_all=0.7511
  08/15 loss_low=0.55119 accuracy_all=0.7540
  09/15 loss_low=0.54105 accuracy_all=0.7578
  10/15 loss_low=0.54020 accuracy_all=0.7620
  11/15 loss_low=0.52657 accuracy_all=0.7742
  12/15 loss_low=0.52642 accuracy_all=0.7760
  13/15 loss_low=0.51881 accuracy_all=0.7772
  14/15 loss_low=0.51894 accuracy_all=0.7849
  15/15 loss_low=0.51603 accuracy_all=0.7762
  development EASE: 0.1533870646725303
NCO25 ratio=0.40; removed per layer=[43, 35, 42]
  01/15 loss_low=0.62862 accuracy_all=0.6866
  02/15 loss_low=0.59557 accuracy_all=0.7073
  03/15 loss_low=0.58419 accuracy_all=0.7100
  04/15 loss_low=0.58226 accuracy_all=0.7196
  05/15 loss_low=0.57365 accuracy_all=0.7327
  06/15 loss_low=0.56908 accuracy_all=0.7279
  07/15 loss_low=0.56451 accuracy_all=0.7402
  08/15 loss_low=0.55859 accuracy_all=0.7318
  09/15 loss_low=0.56024 accuracy_all=0.7493
  10/15 loss_low=0.54980 accuracy_all=0.7444
  11/15 loss_low=0.54317 accuracy_all=0.7521
  12/15 loss_low=0.53726 accuracy_all=0.7648
  13/15 loss_low=0.53252 accuracy_all=0.7674
  14/15 loss_low=0.53291 accuracy_all=0.7625
  15/15 loss_low=0.53280 accuracy_all=0.7659
  development EASE: 0.2190047234253914
NCO25 ratio=0.45; removed per layer=[47, 43, 45]
  01/15 loss_low=0.63380 accuracy_all=0.6590
  02/15 loss_low=0.60415 accuracy_all=0.6850
  03/15 loss_low=0.59224 accuracy_all=0.6986
  04/15 loss_low=0.58868 accuracy_all=0.7055
  05/15 loss_low=0.58063 accuracy_all=0.7181
  06/15 loss_low=0.57566 accuracy_all=0.7213
  07/15 loss_low=0.57586 accuracy_all=0.7249
  08/15 loss_low=0.56744 accuracy_all=0.7294
  09/15 loss_low=0.56199 accuracy_all=0.7256
  10/15 loss_low=0.56033 accuracy_all=0.7319
  11/15 loss_low=0.55257 accuracy_all=0.7494
  12/15 loss_low=0.54495 accuracy_all=0.7475
  13/15 loss_low=0.54526 accuracy_all=0.7526
  14/15 loss_low=0.53897 accuracy_all=0.7531
  15/15 loss_low=0.54252 accuracy_all=0.7527
  development EASE: 0.21527336127641553
NCO25 ratio=0.50; removed per layer=[51, 48, 51]
  01/15 loss_low=0.63536 accuracy_all=0.6527
  02/15 loss_low=0.61162 accuracy_all=0.6718
  03/15 loss_low=0.60046 accuracy_all=0.6925
  04/15 loss_low=0.59491 accuracy_all=0.7015
  05/15 loss_low=0.58927 accuracy_all=0.7055
  06/15 loss_low=0.58135 accuracy_all=0.7124
  07/15 loss_low=0.58067 accuracy_all=0.7080
  08/15 loss_low=0.57815 accuracy_all=0.7199
  09/15 loss_low=0.57342 accuracy_all=0.7210
  10/15 loss_low=0.56953 accuracy_all=0.7351
  11/15 loss_low=0.56179 accuracy_all=0.7280
  12/15 loss_low=0.56004 accuracy_all=0.7370
  13/15 loss_low=0.55298 accuracy_all=0.7374
  14/15 loss_low=0.55575 accuracy_all=0.7415
  15/15 loss_low=0.54894 accuracy_all=0.7388
  development EASE: 0.20851320207914587
Selected ratio (development EASE only): 0.35
NCO25 pruning/fine-tuning seconds: 8.51

   ratio  development_EASE removed_per_layer retained_per_layer
0   0.35          0.153387      [35, 31, 39]       [65, 69, 61]
1   0.40          0.219005      [43, 35, 42]       [57, 65, 58]
2   0.45          0.215273      [47, 43, 45]       [53, 57, 55]
3   0.50          0.208513      [51, 48, 51]       [49, 52, 49]

True RR=0.75; same 1000 paired outcome realizations

,method,heldout_EASE,mean_rr,mae_rr,rmse_rr
0,Base Model,0.250688,0.875081,0.125311,0.135511
1,UNO (75% development NCOs without U),0.235264,0.838985,0.090149,0.103054

,comparison,MAE_difference,MSE_difference,relative_RMSE_reduction,fraction_UNO_lower_absolute_error
0,NCO25 UNO minus Base Model,-0.035162,-0.007743,0.239514,0.875

Original data, fitted Base, original UNO predictions (if present), and Y realizations: unchanged.
One fixed cohort and one specified NCO perturbation; only the original Y realizations are repeated.

,no_U_percent,method,heldout_EASE,mean_rr,mae_rr,rmse_rr
0,10,Base Model,0.250688,0.875081,0.125311,0.135511
1,10,UNO (10% development NCOs without U),0.221743,0.830804,0.082201,0.093935
2,25,Base Model,0.250688,0.875081,0.125311,0.135511
3,25,UNO (25% development NCOs without U),0.219138,0.841341,0.092558,0.105061
4,50,Base Model,0.250688,0.875081,0.125311,0.135511
5,50,UNO (50% development NCOs without U),0.170971,0.805899,0.060585,0.072816
6,75,Base Model,0.250688,0.875081,0.125311,0.135511
7,75,UNO (75% development NCOs without U),0.235264,0.838985,0.090149,0.103054
8,100,Base Model,0.250688,0.875081,0.125311,0.135511
9,100,UNO (100% development NCOs without U),0.236322,0.870925,0.120996,0.129597

Saved this completed setting: /Users/yuewudb/UNO_revision_ex/benchmark/simulation_benchmark/results/run_20260926T180515467846Z_23447

--- Replacement fraction: 90% ---
Fixed cohort: n=10000; existing Y realizations=1000
Replace 36/40 development NCOs; retain all 40 held-out NCOs.
Original Base parameters, predictions, data and Y realizations will not be overwritten.

,nco,df_column_index,replaced,original_U_loading,scenario_U_loading,prevalence_original,prevalence_scenario,prevalence_treated,prevalence_control,estimable
0,W38,58,True,0.988957,0.0,0.1122,0.0911,0.119414,0.072003,True
1,W65,85,True,1.110496,0.0,0.1815,0.1684,0.215243,0.136805,True
2,W37,57,True,1.352575,0.0,0.1297,0.1049,0.130586,0.087575,True
3,W04,24,True,1.290683,0.0,0.1074,0.0818,0.106256,0.065305,True
4,W01,21,True,1.177141,0.0,0.0802,0.0606,0.073734,0.051741,True
5,W41,61,True,1.287191,0.0,0.1512,0.1310,0.166336,0.107167,True
6,W79,99,True,1.082868,0.0,0.0650,0.0523,0.069762,0.040522,True
7,W56,76,True,1.040880,0.0,0.1366,0.1218,0.158640,0.096952,True
8,W32,52,True,1.174736,0.0,0.1801,0.1541,0.189921,0.129940,True
9,W42,62,True,1.226049,0.0,0.1024,0.0817,0.109235,0.063128,True
10,W66,86,True,1.055397,0.0,0.1999,0.1805,0.228401,0.148192,True
11,W76,96,True,1.084402,0.0,0.1301,0.1202,0.154171,0.097287,True
12,W48,68,True,1.006070,0.0,0.0818,0.0720,0.102036,0.051741,True
13,W53,73,True,1.031342,0.0,0.1167,0.1036,0.145978,0.075017,True
14,W10,30,True,1.132906,0.0,0.1032,0.0879,0.117180,0.068151,True
15,W18,38,True,0.983912,0.0,0.1070,0.0933,0.125124,0.071835,True
16,W64,84,True,1.166224,0.0,0.0749,0.0582,0.076216,0.046048,True
17,W74,94,True,1.184736,0.0,0.1932,0.1694,0.204568,0.145680,True
18,W26,46,True,1.214154,0.0,0.1041,0.0808,0.092850,0.072672,True
19,W39,59,True,1.044396,0.0,0.1651,0.1605,0.203823,0.131279,True
20,W49,69,True,1.347693,0.0,0.1525,0.1349,0.168570,0.112190,True
21,W34,54,True,1.188540,0.0,0.1302,0.1060,0.131827,0.088580,True
22,W21,41,True,1.258917,0.0,0.1284,0.1069,0.138779,0.085399,True
23,W68,88,True,1.387916,0.0,0.1114,0.0853,0.108987,0.069324,True
24,W08,28,True,0.915232,0.0,0.0743,0.0650,0.085899,0.050904,True
25,W28,48,True,0.939815,0.0,0.1327,0.1139,0.155164,0.086068,True
26,W55,75,True,0.910472,0.0,0.1039,0.1027,0.136048,0.080208,True
27,W03,23,True,1.020313,0.0,0.1140,0.0981,0.130089,0.076524,True
28,W75,95,True,1.143779,0.0,0.1825,0.1691,0.225174,0.131279,True
29,W70,90,True,1.343506,0.0,0.1041,0.0768,0.099305,0.061621,True
30,W52,72,True,1.175688,0.0,0.1054,0.0902,0.125869,0.066142,True
31,W30,50,True,1.060758,0.0,0.0817,0.0725,0.087637,0.062291,True
32,W57,77,True,1.035340,0.0,0.1282,0.1153,0.158640,0.086068,True
33,W27,47,True,1.269630,0.0,0.0897,0.0727,0.097815,0.055760,True
34,W07,27,True,1.382685,0.0,0.1806,0.1625,0.202830,0.135298,True
35,W02,22,True,1.119073,0.0,0.1404,0.1186,0.156653,0.092934,True

Unchanged: all non-replaced development NCOs and all held-out NCO observations.
NCO25: fitted 10/40 development NCO model pairs
NCO25: fitted 20/40 development NCO model pairs
NCO25: fitted 30/40 development NCO model pairs
NCO25: fitted 40/40 development NCO model pairs
Estimated signals may be nonzero even for NCOs with no direct U dependence.

   replaced  n_ncos  mean_absolute_estimated_signal
0     False       4                        0.044886
1      True      36                        0.034507

   signal_threshold  count_offset  count_cutoff  n_high  n_low  high_fraction
0              0.08             3            10    1031   8969         0.1031

Inherited Base architecture: {'in_N': 20, 'm': 100, 'depth': 3, 'dropout': 0.1, 'ps_floor': 0.01}
Candidate ratios: (0.35, 0.4, 0.45, 0.5) | fine-tuning epochs: 15
NCO25 ratio=0.35; removed per layer=[34, 32, 39]
  01/15 loss_low=0.61101 accuracy_all=0.6986
  02/15 loss_low=0.58121 accuracy_all=0.7247
  03/15 loss_low=0.57274 accuracy_all=0.7296
  04/15 loss_low=0.56596 accuracy_all=0.7372
  05/15 loss_low=0.56143 accuracy_all=0.7374
  06/15 loss_low=0.55842 accuracy_all=0.7451
  07/15 loss_low=0.55400 accuracy_all=0.7465
  08/15 loss_low=0.54783 accuracy_all=0.7552
  09/15 loss_low=0.54031 accuracy_all=0.7591
  10/15 loss_low=0.54319 accuracy_all=0.7632
  11/15 loss_low=0.52679 accuracy_all=0.7720
  12/15 loss_low=0.52115 accuracy_all=0.7760
  13/15 loss_low=0.51855 accuracy_all=0.7712
  14/15 loss_low=0.51396 accuracy_all=0.7809
  15/15 loss_low=0.51289 accuracy_all=0.7813
  development EASE: 0.12148651349193325
NCO25 ratio=0.40; removed per layer=[43, 34, 43]
  01/15 loss_low=0.62302 accuracy_all=0.6792
  02/15 loss_low=0.59361 accuracy_all=0.6919
  03/15 loss_low=0.58322 accuracy_all=0.7043
  04/15 loss_low=0.58166 accuracy_all=0.7131
  05/15 loss_low=0.57307 accuracy_all=0.7279
  06/15 loss_low=0.56761 accuracy_all=0.7276
  07/15 loss_low=0.56139 accuracy_all=0.7365
  08/15 loss_low=0.56195 accuracy_all=0.7392
  09/15 loss_low=0.55804 accuracy_all=0.7405
  10/15 loss_low=0.55392 accuracy_all=0.7444
  11/15 loss_low=0.54080 accuracy_all=0.7574
  12/15 loss_low=0.53481 accuracy_all=0.7545
  13/15 loss_low=0.53608 accuracy_all=0.7633
  14/15 loss_low=0.53000 accuracy_all=0.7639
  15/15 loss_low=0.53167 accuracy_all=0.7710
  development EASE: 0.15201084324907085
NCO25 ratio=0.45; removed per layer=[49, 40, 46]
  01/15 loss_low=0.63132 accuracy_all=0.6687
  02/15 loss_low=0.60109 accuracy_all=0.6832
  03/15 loss_low=0.59343 accuracy_all=0.7014
  04/15 loss_low=0.58478 accuracy_all=0.7111
  05/15 loss_low=0.57938 accuracy_all=0.7170
  06/15 loss_low=0.57640 accuracy_all=0.7214
  07/15 loss_low=0.57264 accuracy_all=0.7229
  08/15 loss_low=0.57004 accuracy_all=0.7299
  09/15 loss_low=0.56407 accuracy_all=0.7192
  10/15 loss_low=0.56277 accuracy_all=0.7270
  11/15 loss_low=0.55285 accuracy_all=0.7459
  12/15 loss_low=0.54982 accuracy_all=0.7495
  13/15 loss_low=0.54598 accuracy_all=0.7478
  14/15 loss_low=0.54510 accuracy_all=0.7520
  15/15 loss_low=0.54444 accuracy_all=0.7569
  development EASE: 0.17149061687172543
NCO25 ratio=0.50; removed per layer=[52, 45, 53]
  01/15 loss_low=0.63407 accuracy_all=0.6539
  02/15 loss_low=0.60712 accuracy_all=0.6715
  03/15 loss_low=0.59610 accuracy_all=0.6926
  04/15 loss_low=0.59509 accuracy_all=0.7050
  05/15 loss_low=0.58864 accuracy_all=0.7065
  06/15 loss_low=0.58489 accuracy_all=0.7052
  07/15 loss_low=0.58084 accuracy_all=0.7164
  08/15 loss_low=0.57216 accuracy_all=0.7171
  09/15 loss_low=0.56572 accuracy_all=0.7207
  10/15 loss_low=0.56503 accuracy_all=0.7291
  11/15 loss_low=0.56310 accuracy_all=0.7355
  12/15 loss_low=0.55195 accuracy_all=0.7341
  13/15 loss_low=0.55094 accuracy_all=0.7392
  14/15 loss_low=0.54500 accuracy_all=0.7402
  15/15 loss_low=0.54802 accuracy_all=0.7438
  development EASE: 0.18337090592330021
Selected ratio (development EASE only): 0.35
NCO25 pruning/fine-tuning seconds: 8.81

   ratio  development_EASE removed_per_layer retained_per_layer
0   0.35          0.121487      [34, 32, 39]       [66, 68, 61]
1   0.40          0.152011      [43, 34, 43]       [57, 66, 57]
2   0.45          0.171491      [49, 40, 46]       [51, 60, 54]
3   0.50          0.183371      [52, 45, 53]       [48, 55, 47]

True RR=0.75; same 1000 paired outcome realizations

,method,heldout_EASE,mean_rr,mae_rr,rmse_rr
0,Base Model,0.250688,0.875081,0.125311,0.135511
1,UNO (90% development NCOs without U),0.243006,0.823824,0.076417,0.090151

,comparison,MAE_difference,MSE_difference,relative_RMSE_reduction,fraction_UNO_lower_absolute_error
0,NCO25 UNO minus Base Model,-0.048894,-0.010236,0.334732,0.915

Original data, fitted Base, original UNO predictions (if present), and Y realizations: unchanged.
One fixed cohort and one specified NCO perturbation; only the original Y realizations are repeated.

,no_U_percent,method,heldout_EASE,mean_rr,mae_rr,rmse_rr
0,10,Base Model,0.250688,0.875081,0.125311,0.135511
1,10,UNO (10% development NCOs without U),0.221743,0.830804,0.082201,0.093935
2,25,Base Model,0.250688,0.875081,0.125311,0.135511
3,25,UNO (25% development NCOs without U),0.219138,0.841341,0.092558,0.105061
4,50,Base Model,0.250688,0.875081,0.125311,0.135511
5,50,UNO (50% development NCOs without U),0.170971,0.805899,0.060585,0.072816
6,75,Base Model,0.250688,0.875081,0.125311,0.135511
7,75,UNO (75% development NCOs without U),0.235264,0.838985,0.090149,0.103054
8,90,Base Model,0.250688,0.875081,0.125311,0.135511
9,90,UNO (90% development NCOs without U),0.243006,0.823824,0.076417,0.090151
10,100,Base Model,0.250688,0.875081,0.125311,0.135511
11,100,UNO (100% development NCOs without U),0.236322,0.870925,0.120996,0.129597

Saved this completed setting: /Users/yuewudb/UNO_revision_ex/benchmark/simulation_benchmark/results/run_20260926T180526037487Z_23447

--- Replacement fraction: 100% ---
Fixed cohort: n=10000; existing Y realizations=1000
Replace 40/40 development NCOs; retain all 40 held-out NCOs.
Original Base parameters, predictions, data and Y realizations will not be overwritten.

,nco,df_column_index,replaced,original_U_loading,scenario_U_loading,prevalence_original,prevalence_scenario,prevalence_treated,prevalence_control,estimable
0,W38,58,True,0.988957,0.0,0.1122,0.0967,0.128352,0.075352,True
1,W65,85,True,1.110496,0.0,0.1815,0.1702,0.217478,0.138312,True
2,W37,57,True,1.352575,0.0,0.1297,0.1047,0.130338,0.087408,True
3,W04,24,True,1.290683,0.0,0.1074,0.0868,0.106504,0.073510,True
4,W54,74,True,1.108142,0.0,0.1191,0.1007,0.131082,0.080208,True
5,W01,21,True,1.177141,0.0,0.0802,0.0639,0.073982,0.057100,True
6,W41,61,True,1.287191,0.0,0.1512,0.1290,0.167080,0.103315,True
7,W79,99,True,1.082868,0.0,0.0650,0.0547,0.075472,0.040690,True
8,W56,76,True,1.040880,0.0,0.1366,0.1199,0.154419,0.096618,True
9,W32,52,True,1.174736,0.0,0.1801,0.1568,0.201092,0.126926,True
10,W42,62,True,1.226049,0.0,0.1024,0.0839,0.112463,0.064635,True
11,W66,86,True,1.055397,0.0,0.1999,0.1807,0.224926,0.150871,True
12,W76,96,True,1.084402,0.0,0.1301,0.1190,0.158391,0.092431,True
13,W16,36,True,0.936948,0.0,0.1598,0.1513,0.193644,0.122739,True
14,W48,68,True,1.006070,0.0,0.0818,0.0742,0.103277,0.054588,True
15,W53,73,True,1.031342,0.0,0.1167,0.1007,0.143496,0.071835,True
16,W10,30,True,1.132906,0.0,0.1032,0.0861,0.122393,0.061621,True
17,W18,38,True,0.983912,0.0,0.1070,0.0919,0.128848,0.066979,True
18,W64,84,True,1.166224,0.0,0.0749,0.0546,0.069513,0.044541,True
19,W74,94,True,1.184736,0.0,0.1932,0.1709,0.210278,0.144340,True
20,W05,25,True,1.082643,0.0,0.0936,0.0784,0.094340,0.067649,True
21,W26,46,True,1.214154,0.0,0.1041,0.0811,0.101539,0.067314,True
22,W39,59,True,1.044396,0.0,0.1651,0.1616,0.199851,0.135800,True
23,W49,69,True,1.347693,0.0,0.1525,0.1323,0.174777,0.103650,True
24,W34,54,True,1.188540,0.0,0.1302,0.1081,0.134310,0.090422,True
25,W21,41,True,1.258917,0.0,0.1284,0.1050,0.140516,0.081045,True
26,W68,88,True,1.387916,0.0,0.1114,0.0839,0.114697,0.063128,True
27,W08,28,True,0.915232,0.0,0.0743,0.0645,0.080685,0.053583,True
28,W28,48,True,0.939815,0.0,0.1327,0.1174,0.156405,0.091092,True
29,W55,75,True,0.910472,0.0,0.1039,0.1000,0.132820,0.077863,True
30,W03,23,True,1.020313,0.0,0.1140,0.0978,0.130834,0.075519,True
31,W75,95,True,1.143779,0.0,0.1825,0.1695,0.222443,0.133791,True
32,W70,90,True,1.343506,0.0,0.1041,0.0789,0.106008,0.060616,True
33,W52,72,True,1.175688,0.0,0.1054,0.0880,0.117676,0.067984,True
34,W29,49,True,1.231481,0.0,0.1135,0.0985,0.135055,0.073845,True
35,W30,50,True,1.060758,0.0,0.0817,0.0677,0.079692,0.059612,True
36,W57,77,True,1.035340,0.0,0.1282,0.1162,0.154667,0.090255,True
37,W27,47,True,1.269630,0.0,0.0897,0.0732,0.094836,0.058607,True
38,W07,27,True,1.382685,0.0,0.1806,0.1600,0.197865,0.134461,True
39,W02,22,True,1.119073,0.0,0.1404,0.1188,0.146723,0.099967,True

Unchanged: all non-replaced development NCOs and all held-out NCO observations.
NCO25: fitted 10/40 development NCO model pairs
NCO25: fitted 20/40 development NCO model pairs
NCO25: fitted 30/40 development NCO model pairs
NCO25: fitted 40/40 development NCO model pairs
Estimated signals may be nonzero even for NCOs with no direct U dependence.

   replaced  n_ncos  mean_absolute_estimated_signal
0      True      40                        0.034198

   signal_threshold  count_offset  count_cutoff  n_high  n_low  high_fraction
0              0.08             3            13     566   9434         0.0566

NOTE: high fraction is outside the original reference range; rule remains unchanged.
Inherited Base architecture: {'in_N': 20, 'm': 100, 'depth': 3, 'dropout': 0.1, 'ps_floor': 0.01}
Candidate ratios: (0.35, 0.4, 0.45, 0.5) | fine-tuning epochs: 15
NCO25 ratio=0.35; removed per layer=[36, 30, 39]
  01/15 loss_low=0.61144 accuracy_all=0.7016
  02/15 loss_low=0.58701 accuracy_all=0.7278
  03/15 loss_low=0.57562 accuracy_all=0.7345
  04/15 loss_low=0.57461 accuracy_all=0.7367
  05/15 loss_low=0.56364 accuracy_all=0.7494
  06/15 loss_low=0.55713 accuracy_all=0.7409
  07/15 loss_low=0.55560 accuracy_all=0.7580
  08/15 loss_low=0.55155 accuracy_all=0.7598
  09/15 loss_low=0.54775 accuracy_all=0.7643
  10/15 loss_low=0.54611 accuracy_all=0.7655
  11/15 loss_low=0.53372 accuracy_all=0.7727
  12/15 loss_low=0.52720 accuracy_all=0.7810
  13/15 loss_low=0.52570 accuracy_all=0.7755
  14/15 loss_low=0.52304 accuracy_all=0.7850
  15/15 loss_low=0.52085 accuracy_all=0.7873
  development EASE: 0.1694747741950022
NCO25 ratio=0.40; removed per layer=[45, 34, 41]
  01/15 loss_low=0.62705 accuracy_all=0.6800
  02/15 loss_low=0.60063 accuracy_all=0.7045
  03/15 loss_low=0.59022 accuracy_all=0.7199
  04/15 loss_low=0.58373 accuracy_all=0.7235
  05/15 loss_low=0.57450 accuracy_all=0.7340
  06/15 loss_low=0.57538 accuracy_all=0.7344
  07/15 loss_low=0.56978 accuracy_all=0.7439
  08/15 loss_low=0.56630 accuracy_all=0.7423
  09/15 loss_low=0.55923 accuracy_all=0.7519
  10/15 loss_low=0.55818 accuracy_all=0.7472
  11/15 loss_low=0.55080 accuracy_all=0.7567
  12/15 loss_low=0.54381 accuracy_all=0.7613
  13/15 loss_low=0.53758 accuracy_all=0.7648
  14/15 loss_low=0.54336 accuracy_all=0.7715
  15/15 loss_low=0.54008 accuracy_all=0.7685
  development EASE: 0.13611482537549538
NCO25 ratio=0.45; removed per layer=[49, 42, 44]
  01/15 loss_low=0.63584 accuracy_all=0.6760
  02/15 loss_low=0.60579 accuracy_all=0.7032
  03/15 loss_low=0.59592 accuracy_all=0.7075
  04/15 loss_low=0.58732 accuracy_all=0.7215
  05/15 loss_low=0.58556 accuracy_all=0.7253
  06/15 loss_low=0.57900 accuracy_all=0.7247
  07/15 loss_low=0.57809 accuracy_all=0.7323
  08/15 loss_low=0.57068 accuracy_all=0.7358
  09/15 loss_low=0.57025 accuracy_all=0.7405
  10/15 loss_low=0.56431 accuracy_all=0.7428
  11/15 loss_low=0.55531 accuracy_all=0.7500
  12/15 loss_low=0.54970 accuracy_all=0.7545
  13/15 loss_low=0.55183 accuracy_all=0.7522
  14/15 loss_low=0.55010 accuracy_all=0.7522
  15/15 loss_low=0.55188 accuracy_all=0.7540
  development EASE: 0.13126089347877554
NCO25 ratio=0.50; removed per layer=[55, 46, 49]
  01/15 loss_low=0.64484 accuracy_all=0.6582
  02/15 loss_low=0.61853 accuracy_all=0.6964
  03/15 loss_low=0.60381 accuracy_all=0.7072
  04/15 loss_low=0.59811 accuracy_all=0.7085
  05/15 loss_low=0.58945 accuracy_all=0.7153
  06/15 loss_low=0.58630 accuracy_all=0.7182
  07/15 loss_low=0.58021 accuracy_all=0.7216
  08/15 loss_low=0.58018 accuracy_all=0.7286
  09/15 loss_low=0.57643 accuracy_all=0.7325
  10/15 loss_low=0.57662 accuracy_all=0.7319
  11/15 loss_low=0.56688 accuracy_all=0.7389
  12/15 loss_low=0.56036 accuracy_all=0.7427
  13/15 loss_low=0.55976 accuracy_all=0.7418
  14/15 loss_low=0.55495 accuracy_all=0.7463
  15/15 loss_low=0.55601 accuracy_all=0.7457
  development EASE: 0.18766912284030193
Selected ratio (development EASE only): 0.45
NCO25 pruning/fine-tuning seconds: 8.72

   ratio  development_EASE removed_per_layer retained_per_layer
0   0.35          0.169475      [36, 30, 39]       [64, 70, 61]
1   0.40          0.136115      [45, 34, 41]       [55, 66, 59]
2   0.45          0.131261      [49, 42, 44]       [51, 58, 56]
3   0.50          0.187669      [55, 46, 49]       [45, 54, 51]

True RR=0.75; same 1000 paired outcome realizations

,method,heldout_EASE,mean_rr,mae_rr,rmse_rr
0,Base Model,0.250688,0.875081,0.125311,0.135511
1,UNO (100% development NCOs without U),0.236322,0.870925,0.120996,0.129597

,comparison,MAE_difference,MSE_difference,relative_RMSE_reduction,fraction_UNO_lower_absolute_error
0,NCO25 UNO minus Base Model,-0.004315,-0.001568,0.043636,0.56

Original data, fitted Base, original UNO predictions (if present), and Y realizations: unchanged.
One fixed cohort and one specified NCO perturbation; only the original Y realizations are repeated.

,no_U_percent,method,heldout_EASE,mean_rr,mae_rr,rmse_rr
0,10,Base Model,0.250688,0.875081,0.125311,0.135511
1,10,UNO (10% development NCOs without U),0.221743,0.830804,0.082201,0.093935
2,25,Base Model,0.250688,0.875081,0.125311,0.135511
3,25,UNO (25% development NCOs without U),0.219138,0.841341,0.092558,0.105061
4,50,Base Model,0.250688,0.875081,0.125311,0.135511
5,50,UNO (50% development NCOs without U),0.170971,0.805899,0.060585,0.072816
6,75,Base Model,0.250688,0.875081,0.125311,0.135511
7,75,UNO (75% development NCOs without U),0.235264,0.838985,0.090149,0.103054
8,90,Base Model,0.250688,0.875081,0.125311,0.135511
9,90,UNO (90% development NCOs without U),0.243006,0.823824,0.076417,0.090151
10,100,Base Model,0.250688,0.875081,0.125311,0.135511
11,100,UNO (100% development NCOs without U),0.236322,0.870925,0.120996,0.129597

Saved this completed setting: /Users/yuewudb/UNO_revision_ex/benchmark/simulation_benchmark/results/run_20260926T180536515788Z_23447

## 16. Five-column tables and comparison with archived displays

The following tables are calculated from this run, not loaded as expected answers.
The original raw outputs (including additional comparators and metrics) remain
available in the notebook namespace and are exported separately. Archived display
values have only six decimal places and are used solely for this post-run audit.
A discrepancy is reported, never hidden or corrected by replacing computed values.

In [19]:
from benchmark_io import publication_tables, compare_saved_tables

benchmark_table1, benchmark_table2 = publication_tables(globals())
print("Table 1: primary benchmark (true RR = 0.75)")
display(benchmark_table1.round(4))
print("Table 2: development-NCO sensitivity settings completed in this kernel")
display(benchmark_table2.round(4))

benchmark_reference_check = compare_saved_tables(globals())
print("Fresh values match archived displays:", bool(benchmark_reference_check["matches_saved_display"].all()))
display(benchmark_reference_check.groupby("table", as_index=False).agg(
    matched_entries=("matches_saved_display", "sum"),
    total_entries=("matches_saved_display", "size"),
    largest_absolute_difference=("absolute_difference", "max"),
))

Table 1: primary benchmark (true RR = 0.75)

                   method  heldout_EASE  mean_rr  mae_rr  rmse_rr
0              Unadjusted        0.5356   1.1001  0.3501   0.3538
1             Logistic PS        0.3489   0.9498  0.1998   0.2052
2              Base Model        0.2507   0.8751  0.1253   0.1355
3                     UNO        0.1902   0.8039  0.0595   0.0718
4        Logistic PS + EC        0.3489   0.6756  0.0748   0.0814
5         Base Model + EC        0.2507   0.6844  0.0674   0.0772
6  Oracle: true PS (X, U)        0.0711   0.7269  0.0396   0.0487

Table 2: development-NCO sensitivity settings completed in this kernel

               method  heldout_EASE  mean_rr  mae_rr  rmse_rr
0          Base Model        0.2507   0.8751  0.1253   0.1355
1  UNO (0%; original)        0.1902   0.8039  0.0595   0.0718
2           UNO (10%)        0.2217   0.8308  0.0822   0.0939
3           UNO (25%)        0.2191   0.8413  0.0926   0.1051
4           UNO (50%)        0.1710   0.8059  0.0606   0.0728
5           UNO (75%)        0.2353   0.8390  0.0901   0.1031
6           UNO (90%)        0.2430   0.8238  0.0764   0.0902
7          UNO (100%)        0.2363   0.8709  0.1210   0.1296

Fresh values match archived displays: True

         table  matched_entries  total_entries  largest_absolute_difference
0      primary               32             32                 4.991299e-07
1  sensitivity               48             48                 4.921027e-07

## 17. Export the actual run

Save fresh tables, replicate-level results, simulated data, propensity scores,
model weights, masks, RNG states, actual parameters, and installed-package versions
to a new timestamped directory. No previous run is overwritten.

The same export call can be pasted into the **original running notebook kernel**
to preserve the fitted weights underlying its displayed results before restarting.
Saved notebook output alone is not a checkpoint.

In [ ]:
from benchmark_io import save_run
benchmark_output_dir = save_run(globals())
print("Archived this actual run:", benchmark_output_dir)